dist: trusty
language: cpp

cache:
  directories:
    - '$HOME/.sonar/cache'

notifications:
  email: false

addons:
  sonarqube:
  branches:
    - master
    - CITest
    - shadow

before_install:
  - chmod +x tools/ci/before-install.sh
  - tools/ci/before-install.sh

install:
  - chmod +x tools/ci/install.sh
  - tools/ci/install.sh

script:
  - chmod +x tools/ci/build.sh

  - tools/ci/build.sh

  #- make clean

  # Execute some tests
  #- make test
  
  # Run SonarQube analysis
  - sonar-scanner

sudo: required

matrix:
  include:

    - os: linux
      dist: precise
      compiler: gcc
      env: OGRE_VERSION=1.9

    - os: linux
      dist: trusty
      compiler: gcc
      env: OGRE_VERSION=1.9

    - os: linux
      dist: precise
      compiler: clang
      env: OGRE_VERSION=1.9

    - os: linux
      dist: trusty
      compiler: clang
      env: OGRE_VERSION=1.9

